pipeline {
  agent any
  tools {
    nodejs 'node-17.5.0'
  }

  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  stages {
    stage('Get Current UserName') {
      steps{
        sh '/usr/bin/curl -k -s -u \$USERNAME:\$PASSWORD -o /tmp/api.xml \$BUILD_URL/api/xml || true && THE_USERID=`cat /tmp/api.xml | grep -oP \'(?<=<userId>).*?(?=</userId>)\'` && echo -e "\$THE_USERID \\c" > /tmp/user_id.txt'
      }
    }
    stage('Install dependencies') {
      steps {
        sh 'cd jenkins-tests && npm i'
      }
    }
    stage('Run tests') {
      steps {
        sh 'cd jenkins-tests && npm t'
      }
    }
    
  }
}
