pipeline {
  agent any
  tools {
    nodejs 'node-17.5.0'
  }

  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  stages {
    stage('Install dependencies') {
      steps {
        sh 'cd jenkins-tests && npm i'
      }
    }
    stage('Run tests') {
      steps {
        sh 'cd jenkins-tests && npm t'
      }
    }
    stage('Get Current UserName') {
      steps{
        wrap([$class: 'BuildUser']) {
          @GET_BUILD_USER = sh ( script: 'echo "${BUILD_USER}"', returnStdout: true).trim()
        }
      }
    }
  }
}
