pipeline {
  agent any
  tools {
    nodejs 'node-17.5.0'
  }

  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  stages {
    stage('Get Current UserName') {
      steps{
        sh """
            /usr/bin/curl -k -s -u \
            admin:admin -o \
            /tmp/api.xml \
            \$BUILD_URL/api/xml || true 

            THE_USERID=`cat /tmp/api.xml | grep -oP '(?<=<userId>).*?(?=</userId>)'`
            THE_USERNAME=`cat /tmp/api.xml | grep -oP '(?<=<userName>).*?(?=</userName>)'`
            
            echo -e "\$THE_USERID \\c" > /tmp/user_id.txt
            """
            sh 'env > env.txt'
            for (String i : readFile('env.txt').split("\r?\n")) {
                println i
            }
      }
    }
    stage('Install dependencies') {
      steps {
        sh 'cd jenkins-tests && npm i'
      }
    }
    stage('Run tests') {
      steps {
        sh 'cd jenkins-tests && npm t'
      }
    }
    
  }
}
